### ISSUE TITLE
DataStream API samples

### ISSUE THREAD

**Issue by patelsan** [aws-samples/pyflink-getting-started#11]
All the samples are using `Table` API, could you please add `DataStream` API samples? Having hard time getting Flink sample working on Kinesis. Thank you in advance!

**Comment by jeremyber-aws** [comment]
@patelsan we will certainly work on creating Datastream examples--can you refer [here](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/dev/python/datastream_tutorial/) for the time being?
