### ISSUE TITLE
No DataStream API Samples

### ISSUE THREAD

**Issue by patelsan** [aws-samples/pyflink-getting-started#13]
Hello,
All the samples demonstrate the `Table API`, and none uses the `DataStream API`. We have a hard time getting the Kinesis Datastream connector working based on the PyFlink docs here: https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/python/datastream_tutorial/. Please add a sample showing Datastream API and Kinesis Datastream connector. Thank you!

**Comment by jeremyber-aws** [comment]
Hi @patelsan , the Flink Kinesis Data Streams DataStream API Connector currently only exists for v1.16 >, and KDA Flink only supports up to v1.15, so even with a sample this may not run on KDA Flink. Would this sample still be useful to you?

**Comment by jeremyber-aws** [comment]
MSK Datastream example has been created.
https://github.com/aws-samples/pyflink-getting-started/tree/main/pyflink-examples/DatastreamKafkaConnector
