### ISSUE TITLE
Logging in Pyflink Application

### ISSUE THREAD

**Issue by liyunrui** [aws-samples/pyflink-getting-started#20]
Dear AWS,
I'm customer. Recently, I'm using keyProcessFunciton like [1]. I'm wondering does KDA support logging like [2] so that we can see any print information under class I pinpoint on [1].

Many Thanks,
Ray

[1].https://github.com/aws-samples/pyflink-getting-started/blob/main/pyflink-examples/DatastreamKafkaConnector/datastream-kafka-connector-example.py#L49
[2].https://github.com/aws-samples/pyflink-getting-started/tree/main/logging

Note:
My code is very similar to [3], but which is written in Python Instead of Java. But, I'v seen they're using org.slf4j.Logger in KeyProcessedFunction.

**Comment by liyunrui** [comment]
Double check already. It can be seen in CW.

**Comment by jeremyber-aws** [comment]
Hi @liyunrui does your second comment mean that you are successful in logging?
