### ISSUE TITLE
pyflink UDF example doesn't runs correctly

### ISSUE THREAD

**Issue by EugenioG2021** [aws-samples/pyflink-getting-started#23]
I am writing this to report that something on pyflink UDF might be broken.

I have found some trouble following this example https://github.com/aws-samples/pyflink-getting-started/tree/main/pyflink-examples/UDF.

What I have done so far, is that I've tried doing two scripts:

- flink_simple_functional.py This one does not uses the UDF and just does a very simple transformation like multiplying an integer column by 2 and sinking it to the console. This works fine
- flink_simple.py This other one is a copy of the above mentioned code, but besides doing a multiplication by 2, it also derives another column more by using a UDF. That UDF just converts a string column to lowercase

However, the first code works (the one that does not uses the UDF), and the second does not, despite it's a very simple UDF.
Am I doing something wrong? Or are UDF are not supported anymore for AWS Kinesis? 

Here I attach both of my flink files, as well as a third file which is the one I use to populate my Kinesis input_stream  from which both the flink files fetch as source. Just in case it might help to take a look at how that stream looks like. It only has one shard and I confirm it has data.

[flink_simple_functional.txt](https://github.com/aws-samples/pyflink-getting-started/files/12006020/flink_simple_functional.txt)
[stock.txt](https://github.com/aws-samples/pyflink-getting-started/files/12006019/stock.txt)
[flink_simple.txt](https://github.com/aws-samples/pyflink-getting-started/files/12006021/flink_simple.txt)

**Comment by xmubeta** [comment]
I tried this example and did not work out yet. There is nothing output.  It seems that the UDF cannot work. 

If you have figured out, please help. Thank you

**Comment by EugenioGastelumGBR** [comment]
I couldn't manage to make it run on kinesis, I switched from Kinesis to hosting flink from helm's chart by using flink deployment operator. There it worked

**Comment by xmubeta** [comment]
Finally I got it worked. I found there was a bug when writing CSV files to S3.   -- https://issues.apache.org/jira/browse/FLINK-28513. After changing to JSON, it worked now.

Another thing to be noticed, checkpointing is needed to configure when writing to S3 for CSV/JSON files.

**Comment by EugenioG2021** [comment]
Great! Thanks a lot for sharing the solution!
