### ISSUE TITLE
Example for packaging a more complicated application

### ISSUE THREAD

**Issue by ducanhkhu-roo** [aws-samples/pyflink-getting-started#3]
Hi, I have a monolith application which has the following layout:

```
.
├── app1_main.py
├── app2_main.py
├── boto3
...
├── botocore
...
├── apps
│   ├── __init__.py
│   ├── app2
│   │   ├── __init__.py
│   │   ├── func_map2.py
│   │   └── func_filter2.py
│   ├── app1
│   │   ├── __init__.py
│   │   ├── func_map1.py
│   │   └── func_filter1.py
│   ├── common
│   │   ├── __init__.py
│   │   ├── config.py
│   │   └── util.py
├── lib
│   └──my-apps-SNAPSHOT.jar
```

This structure works fine locally with `flink run --python apps/app1_main.py --pyFiles apps`. I also followed [another example](https://github.com/aws-samples/amazon-kinesis-data-analytics-examples/tree/master/python/PythonPackages) for PyFlink packaging for KDA and cannot get it to work. The error that I'm getting is: `ModuleNotFoundError: No module named 'app1'`. It looks like KDA doesn't recognise my package or it doesn't add additional packages will be available in the base path. 

Both this example and the other one don't mention user defined packages. Is it supported? How do I structure a more complex application with packages? Many thanks.

**Comment by jeremyber-aws** [comment]
Hi @ducanhkhu-roo please review the newly added PythonPackages section of our [packaging instructions](https://github.com/aws-samples/pyflink-getting-started/tree/main/packaging) and let know if this helps.

**Comment by ducanhkhu-roo** [comment]
thanks @jeremyber-aws for updating the doc. It looks good 👍
