### ISSUE TITLE
Pyflink and AWS Glue integration

### ISSUE THREAD

**Issue by rnekkanti2** [aws-samples/pyflink-getting-started#9]
I am trying to integrate the pyflink table API table creation with AWS glue catalog where I need not create my source and sink tables every time or manage them separately. I am not finding any documentation or samples in AWS repos. I would like to know if KDA supports pyflink glue catalog integration, if so can you add a couple of samples showing how it works.

**Comment by jeremyber-aws** [comment]
In Kinesis Data Analytics for Apache Flink (durable application), it is not possible to integrate with the glue data catalog natively today. However, you can integrate with the Glue Data Catalog if you create your application on [Kinesis Data Analytics Studio](https://docs.aws.amazon.com/kinesisanalytics/latest/java/how-zeppelin-glue.html) which has an integrated glue data catalog database. This database will be referred to when you deploy your application from Kinesis Data Analytics Studio as well.
